# Generated by Django 3.1.4 on 2021-03-22 09:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2021, 3, 22, 9, 35, 49, 393362, tzinfo=utc), max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
