# Generated by Django 3.1.4 on 2021-03-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('logged_in_user_id', models.IntegerField()),
            ],
        ),
    ]
